export interface SearchResponse {
  total: number
  objectIDs: Array<number>
}

export interface Constituent {
  constituentID: number
  constituentULAN_URL: string
  constituentWikidata_URL: URL
  gender: string
  name: string
}

export interface ArtObject {
  GalleryNumber: string,
  accessionNumber: string,
  accessionYear: string,
  additionalImages: Array<string>,
  artistAlphaSort: string,
  artistBeginDate: string,
  artistDisplayBio: string,
  artistDisplayName: string,
  artistEndDate: string,
  artistGender: string,
  artistNationality: string,
  artistPrefix: string,
  artistRole: string,
  artistSuffix: string,
  artistULAN_URL: URL
  artistWikidata_URL: URL
  constituents: Array<Constituent>,
  city: string,
  classification: string,
  country: string,
  county: string,
  creditLine: string,
  culture: string,
  department: string,
  dimensions: string,
  dynasty: string,
  excavation: string,
  geographyType: string,
  isHighlight: boolean,
  isPublicDomain: boolean,
  isTimelineWork: boolean,
  linkResource: string,
  locale: string,
  locus: string,
  measurements: any,
  medium: string,
  metadataDate: string,
  objectBeginDate: number,
  objectDate: string,
  objectEndDate: number,
  objectID: number,
  objectName: string,
  objectURL: string,
  objectWikidata_URL: string,
  period: string,
  portfolio: string,
  primaryImage: string,
  primaryImageSmall: string,
  region: string,
  repository: string,
  rightsAndReproduction: string,
  river: string,
  state: string,
  title: string,
}
export const TEMPLATE_ART_OBJECT = {
  GalleryNumber: "",
  accessionNumber: "1979.486.1",
  accessionYear: "1979",
  additionalImages: [],
  artistAlphaSort: "Longacre, James Barton",
  artistBeginDate: "1794",
  artistDisplayBio: "American, Delaware County, Pennsylvania 1794–1869 Philadelphia, Pennsylvania",
  artistDisplayName: "James Barton Longacre",
  artistEndDate: "1869",
  artistGender: "",
  artistNationality: "American",
  artistPrefix: "",
  artistRole: "Maker",
  artistSuffix: "",
  artistULAN_URL: "http://vocab.getty.edu/page/ulan/500011409",
  artistWikidata_URL: "https://www.wikidata.org/wiki/Q3806459",
  city: "",
  classification: "",
  constituents: [],
  country: "",
  county: "",
  creditLine: "Gift of Heinz L. Stoppelmann, 1979",
  culture: "",
  department: "The American Wing",
  dimensions: "Dimensions unavailable",
  dynasty: "",
  excavation: "",
  geographyType: "",
  isHighlight: false,
  isPublicDomain: false,
  isTimelineWork: false,
  linkResource: "",
  locale: "",
  locus: "",
  measurements: null,
  medium: "Gold",
  metadataDate: "2021-04-06T04:41:04.967Z",
  objectBeginDate: 1853,
  objectDate: "1853",
  objectEndDate: 1853,
  objectID: 1,
  objectName: "Coin",
  objectURL: "https://www.metmuseum.org/art/collection/search/1",
  objectWikidata_URL: "",
  period: "",
  portfolio: "",
  primaryImage: "",
  primaryImageSmall: "",
  region: "",
  repository: "Metropolitan Museum of Art, New York, NY",
  rightsAndReproduction: "",
  river: "",
  state: "",
  title: "One-dollar Liberty Head Coin",
}
